# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3d11a3b83865a6d8f1767d880ed0226980beea617d4ad4e919e841ce809f61c4cc4ec0723f4f843ff9072a36cef78277e75f2cba04f1ae3a1224a05a26b0fd

test:
  secret_key_base: e4d2d01a28f972b82db796d857a3e2c18c877ae2a597322b0c604590678ac6903f62fa6fa82e4b39942e31d3682577d8d91bdcad1035382fadf5445e93bcf4a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
